<a href="https://colab.research.google.com/github/sadmandiu/AI-lab/blob/main/lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

#1D array
arr = np.array([1, 2, 7, 4, 5])
print(arr)

#2D array
arr = np.array([[11, 22, 33], [44, 55, 66]])
print(arr)

#3D array
arr = np.array([[[1, 2, 3], [40, 50, 60]], [[1, 2, 3], [40, 50, 60]]]) #need '2' 2D array
print(arr)

# dimentions of array
arr1 = np.array(95)
arr2 = np.array([61,72,90])
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

[1 2 7 4 5]
[[11 22 33]
 [44 55 66]]
[[[ 1  2  3]
  [40 50 60]]

 [[ 1  2  3]
  [40 50 60]]]
0
1
2
3


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])


#3rd element of 1st row
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('3rd element of 1st row: ', arr[0, 2])


#last element of 2nd row
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('last element on 2nd row: ', arr[1, 4])

7
3rd element of 1st row:  3
last element on 2nd row:  10


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4])  #from index 1 to index 3

print(arr[2:])  #from index 2 to last index

print(arr[:5])  #from index 0 to index 4

print(arr[-3:-1])

print(arr[1:5:3]) #3 means index = (i= i+3)

print(arr[::2]) #from first to last, index difference is 2

[2 3 4]
[3 4 5 6 7]
[1 2 3 4 5]
[5 6]
[2 5]
[1 3 5 7]


In [ ]:
# '0' means row1, '1' means row2

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

#From both rows, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

#From both elements, slice index 1 to index 3, returns a 2-D array
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [8]:
import numpy as np

#copy is a new array, the original array will not be changed
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


#view changes the main array too.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np
#1D
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

#2D
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

#1D to 2D convertr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3,4)
print(newarr)

#1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

(5,)
(2, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
#print all the elements one by one,in a single column
for x in arr:
  print(x)


#print array elements as it is
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

#print all the elements under a single column
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
#Axis 0 measn row , Axis 1 means column

import numpy as np

#by default same row te boshbe
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


#print 2nd array as a new row
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


arr = np.array(['iphone', 'xiaomi', 'nokia'])
print(np.sort(arr))


arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
['iphone' 'nokia' 'xiaomi']
[[2 3 4]
 [0 1 5]]
